version: "3.0"

services:
  
  # Zooei database
  mariadb:
    image: mariadb:10.4.31
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=zooei
    ports:
      - 3306:3306
  
  # Zooei app
  app:
    image: zooei/stable:1.0
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
    links:
      - mariadb
    depends_on:
      - mariadb
    tty: true
