version: "3.0"

services:
  database:
    image: mariadb:10.4.31
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=zooei
    ports:
      - 3306:3306
  web:
    image: zooei/stable:1.0
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
    links:
      - database
    depends_on:
      - database
    tty: true
