USE zooei;

-- Create board table
CREATE TABLE IF NOT EXISTS zooei.boards_tbl (
    board_id INT AUTO_INCREMENT NOT NULL,
    board_category VARCHAR(10) NOT NULL,
    board_uri VARCHAR(50) NOT NULL,
    board_title VARCHAR(50) NOT NULL,

    PRIMARY KEY (board_id)
);

-- Populate board table (intr = Interests; brl = Brazil)
INSERT INTO zooei.boards_tbl (
    board_category,
    board_uri,
    board_title
) VALUES ("intr", "/anime", "Anime"),
    ("intr", "/cosplay", "Cosplay"),
    ("intr", "/youtube", "YouTube"),
    ("intr", "/games", "Games"),
    ("intr", "/retro-games", "Retrô Games"),
    ("intr", "/rpg", "RPG"),
    ("intr", "/brinquedos-action-figures", "Brinquedos/Action Figures"),
    ("intr", "/quadrinhos", "Quadrinhos"),
    ("intr", "/tecnologia", "Tecnologia"),
    ("intr", "/televisao", "Televisão"),
    ("intr", "/filmes", "Filmes"),
    ("intr", "/armas", "Armas"),
    ("intr", "/natureza", "Natureza"),
    ("intr", "/animais", "Animais"),
    ("intr", "/esportes", "Esportes"),
    ("intr", "/ciencias", "Ciências"),
    ("intr", "/matematica", "Matemática"),
    ("intr", "/historia-humanidades", "História/Humanidades"),
    ("intr", "/literatura", "Literatura"),
    ("intr", "/politica", "Política"),
    ("intr", "/fotografia", "Fotografia"),
    ("intr", "/design-grafico", "Design Gráfico"),
    ("intr", "/papel-de-parede", "Papel de Parede"),
    ("intr", "/musica", "Música"),
    ("intr", "/faca-voce-mesmo", "Faça Você Mesmo"),
    ("brl", "/br", "Brasil (BR)"),
    ("brl", "/ac", "Acre (AC)"),
    ("brl", "/al", "Alagoas (AL)"),
    ("brl", "/ap", "Amapá (AP)"),
    ("brl", "/am", "Amazonas (AM)"),
    ("brl", "/ba", "Bahia (BA)"),
    ("brl", "/ce", "Ceará (CE)"),
    ("brl", "/es", "Espírito Santo (ES)"),
    ("brl", "/go", "Goiás (GO)"),
    ("brl", "/ma", "Maranhão (MA)"),
    ("brl", "/mt", "Mato Grosso (MT)"),
    ("brl", "/ms", "Mato Grosso do Sul (MS)"),
    ("brl", "/mg", "Minas Gerais (MG)"),
    ("brl", "/pa", "Pará (PA)"),
    ("brl", "/pb", "Paraíba (PB)"),
    ("brl", "/pr", "Paraná (PR)"),
    ("brl", "/pe", "Pernanbuco (PE)"),
    ("brl", "/pi", "Piauí (PI)"),
    ("brl", "/rj", "Rio de Janeiro (RJ)"),
    ("brl", "/rn", "Rio Grande do Norte (RN)"),
    ("brl", "/rs", "Rio Grande do Sul (RS)"),
    ("brl", "/ro", "Rondônia (RO)"),
    ("brl", "/rr", "Roraima (RR)"),
    ("brl", "/sc", "Santa Catarina (SC)"),
    ("brl", "/sp", "São Paulo (SP)"),
    ("brl", "/se", "Sergipe (SE)"),
    ("brl", "/to", "Tocantins (TO)"),
    ("brl", "/df", "Distrito Federal (DF)");
